---
title: MFNttps

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md', '/CONTRIBUTING.md']

permalink: pretty

collections:
  mfnttps:
    output: true

defaults:
  - scope:
      path: '_mfnttps'
    values:
      layout: ttp
